using Invoices.Api.Models;
using Invoices.Data.Entities;

namespace Invoices.Api.Services.Statistics
{
    /// <summary>
    /// Provides logic for calculating revenue statistics for individual persons or companies.
    /// </summary>
    /// <remarks>
    /// This calculator performs in-memory aggregation of invoices and associates them
    /// with existing (non-hidden) persons. It does not access the database directly;
    /// all required data must be supplied via method parameters.
    ///
    /// Hidden persons are automatically excluded from the calculation.
    /// Only invoices referencing an existing, non-hidden person are included.
    /// </remarks>
    public class PersonStatisticsCalculator : IPersonStatisticsCalculator
    {
        /// <summary>
        /// Calculates revenue statistics for all visible persons based on the provided invoices.
        /// </summary>
        /// <param name="persons">
        /// A collection of <see cref="Person"/> entities. Hidden persons are ignored.
        /// </param>
        /// <param name="invoices">
        /// A collection of <see cref="Invoice"/> entities used to compute revenue totals.
        /// Only invoices whose <c>SellerId</c> matches an existing, non-hidden person are included.
        /// </param>
        /// <returns>
        /// A collection of <see cref="PersonStatisticsDto"/> objects, each containing:
        /// <list type="bullet">
        /// <item><description>The person's identifier.</description></item>
        /// <item><description>The person's display name.</description></item>
        /// <item><description>The total revenue generated by that person.</description></item>
        /// </list>
        /// The result is ordered in descending order by revenue.
        /// </returns>
        public IEnumerable<PersonStatisticsDto> Calculate(
            IEnumerable<Person> persons,
            IEnumerable<Invoice> invoices
        )
        {
            var personDict = persons
                .Where(p => !p.Hidden)
                .ToDictionary(p => p.PersonId);

            var stats = invoices
                .Where(i => personDict.ContainsKey(i.SellerId))
                .GroupBy(i => i.SellerId)
                .Select(g => new PersonStatisticsDto
                {
                    PersonId = g.Key,
                    PersonName = personDict[g.Key].Name,
                    Revenue = g.Sum(i => i.Price)
                })
                .OrderByDescending(s => s.Revenue);

            return stats;
        }
    }
}
